clair:
  database:
    type: pgsql
    options:
      source: host=postgres port=5432 user=postgres password=password dbname=clair sslmode=disable
      cachesize: 16384
  api:
    port: 6060
    healthport: 6061
    timeout: 900s
  updater:
    interval: 2h
  notifier:
    attempts: 3
    renotifyinterval: 2h